" Vim editor and display settings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" [Vimbits]

" Reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

" Make Y behave like other capitals
map Y y$

" Automatically reload vimrc when it's saved
au BufWritePost .vimrc so ~/.vimrc

" Use sane regexes
nnoremap / /\v
vnoremap / /\v

" Select all
map <Leader>sa ggVG

" End [Vimbits]

" Disable compatibility
set nocompatible

" Hide toolbar by default
if has("gui_running")
	set guioptions=egmrt
endif

" Hide buffers instead of closing them
set hidden

" Disable modelines for security
set modelines=0

" Customize the status bar
set showmode
set showcmd
set laststatus=2    " always shows status bar

" Intelligent line numbers
set rnu
au InsertEnter * :set nu
au InsertLeave * :set rnu
au FocusLost * :set nu
au FocusGained * :set rnu

" Set history and undo levels
set history=1000         " remember more commands and search history
set undolevels=1000      " use many muchos levels of undo

" Ignore some file extensions for tab auto-completion
set wildignore=*.swp,*.bak,*.pyc,*.class

" File editing and backups
"set backupdir=~/.vim/tmp/backup// " backups
"set directory=~/.vim/tmp/swap//   " swap files
"set backup                        " enable backups
"set noswapfile                    " disable swap files

" File loading and saving
set ar                            " auto-reload changed files
:au FocusLost * silent! wa        " save on focus lost
:set autowrite                    " save on buffer switch

" Encoding / end of file (EOF) settings
set encoding=utf-8
set binary noeol 	" do NOT put a carriage return at the end of the last line! if you are programming for the web the default will cause http headers to be sent. that's bad.

" General display settings
set vb							" turn on the "visual bell" - which is much quieter than the "audio blink"
"set lines=50 columns=84			" initial window size
set relativenumber				" turn on relative line numbers
set ruler						" turn on ruler
set wrap						" turn on soft wrap and word wrap
set linebreak
set guifont=Source\ Code\ Pro:h16	" set default font

" Display settings in insert mode
syntax on           " syntax highlighting
set showmatch       " automatically show matching brackets

" Syntax highlighting
au BufNewFile,BufRead *.less set filetype=css

" Editing in insert mode
set ai              " auto-indenting for programming

" Settings for tabs
set tabstop=6
set shiftwidth=6
"set expandtab

" Filetype stuff
filetype on
filetype plugin on
filetype indent on

" Make autocompletion work like bash's autocompletion
set wildmenu
set wildmode=list:longest

" Settings for search and replace
set incsearch 		" turn on incremental search 
set ignorecase
set smartcase 		" turn on smart case search
set gdefault 		" make regex searching default to global

" Turn on context for page forward and back
set scrolloff=2

" Share clipboard between windows
set clipboard=unnamed


" Key remappings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Change <leader> key
let mapleader = ","

" Change movement keys for Colemak
noremap h k
noremap j h
noremap k j

" Easier page up / page down
noremap H <C-b>
noremap K <C-f>

" One less key (<shift>) to press each time
nnoremap ; :


" Shortcuts for vim
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" <Leader>vrc brings up .vimrc for editing
map <Leader>rc :e $MYVIMRC<CR>

" Split windows
nnoremap <leader>ws <C-w>s<C-w>l

" Moving around split windows
nnoremap <C-j> <C-w>h
nnoremap <C-k> <C-w>j
nnoremap <C-h> <C-w>k
nnoremap <C-l> <C-w>l

nnoremap <leader>wj <C-w>h
nnoremap <leader>wk <C-w>j
nnoremap <leader>wh <C-w>k
nnoremap <leader>wl <C-w>l

" Settings for tab key
nnoremap <leader>t2e :setl ts=2<Enter>:setl sw=2<Enter>:setl expandtab<Enter>
nnoremap <leader>t4e :setl ts=4<Enter>:setl sw=4<Enter>:setl expandtab<Enter>
nnoremap <leader>t4d :setl ts=4<Enter>:setl sw=4<Enter>:setl noexpandtab<Enter>


" Pathogen
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
execute pathogen#infect()


" Vim airline
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
" Fix a weird bug with the first line being broken (https://github.com/zeit/hyper/issues/1037#issuecomment-269848444)
set t_RV=


" Stuff that has to be last
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Set color scheme
syntax enable
set background=dark
colorscheme hybrid_material
