source ~/.dotfiles/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Load bundles.
antigen bundle fasd
antigen bundle gitfast
antigen bundle common-aliases
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-autosuggestions
antigen bundle molovo/tipz
antigen bundle arcanist

# Load autocompletion plugins.
antigen bundle gibo-completion

# Load the theme.
antigen theme frmendes/geometry

# Tell antigen that you're done.
antigen apply

# Set editor to VS Code.
export EDITOR=vim

# Customize prompt.
GEOMETRY_COLOR_DIR="magenta"
PROMPT_GEOMETRY_EXEC_TIME=true
GEOMETRY_PLUGIN_SEPARATOR=" "

# Import bindings.
source ~/.dotfiles/zsh/bindings

# Import functions.
source ~/.dotfiles/zsh/functions

# Import aliases.
source ~/.dotfiles/zsh/aliases

# Import environment variables.
source ~/.dotfiles/zsh/env-vars

# Import changes to PATH.
source ~/.dotfiles/zsh/path

# Load autosuggestions.
source ~/.dotfiles/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# Allow autocompleting to special directories (like ../)
zstyle ':completion:*' special-dirs true

# Load rbenv
if type "rbenv" > /dev/null; then
  eval "$(rbenv init -)"
fi

# NOTE: This theme was disabled because it's too slow
# antigen theme bhilburn/powerlevel9k powerlevel9k
# POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir rbenv vcs)
# POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status history time vi_mode)
# POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
# POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
